# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"

# Inserts a blank line between shell prompts
add_newline = true

# Use custom format
format = """
[$os$shell$username$hostname $python](bold subtext0)\
\n[$time| $directory](bold text)\
(\n[$git_branch$git_commit$git_state $git_metrics$git_status](bold white))\
\n$character"""

# Not working in powershell
# right_format = """
# $git_branch$git_commit$git_state$git_metrics$git_status 
# """

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red)'
disabled = false

# ----- first line -----

[os]
format = "[$symbol]($style)"
style = '$style'
disabled = false

[shell]
powershell_indicator = "\uebc7 "
unknown_indicator = '?_'
style = '$style'
disabled = false

[username]
format = '[$user]($style)'
style_user = 'bold subtext0'
style_root = 'bold red'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$ssh_symbol$hostname]($style)'
style = '$style'
trim_at = '.'
ssh_symbol = " "
disabled = false

# ----- second line -----

[time]
disabled = false
format = "[\ue641 $time]($style) "
time_format = '%R'
style = '$style text'

[directory]
read_only = "󰌾"
style = '$style text'

# ----- third line -----

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
symbol = " "
style = '$style'

[git_commit]
tag_symbol = '  '
style = '$style'

[git_state]
style = '$style'

[git_metrics]
disabled = false

[git_status]
conflicted = '🏳'

ahead = "\uf005d${count}"
diverged = "\uf0e79⇡${ahead_count}⇣${behind_count}"
behind = "\uf0045${count}"

up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'
style = '$style'

# ----- additional -----

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "


[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
