h1_size = 23
h2_size = 17
h3_size = 15
font-size = 13
small_font_size = 12
font_family = JetBrainsMono Nerd Font
font_family_monospace = JetBrainsMono Nerd Font

background = 0xFF232634
base = 0xFF303446
text = 0xFFC6D0F5
alternate_base = 0xFF292C3C
bright_text = 0xFFF2D5CF
accent = 0xFFBABBF1
accent_secondary = 0xFFBABBF1
